resilience4j:
  retry:
    instances:
      rivier:
        resultPredicate: com.mytests.spring.springbootconfigpropsgeneric.originalCase.ConditionalRetryPredicate


my:
  generic:
    props:
      pojo-list:
        - of-foo-children:
            t: mmmm

        - of-foo-children:
            t: nnnn